language: node_js
node_js:
- '0.10'
notifications:
  slack:
    secure: fqTLLWtCUt4JoOp1/OVbjO92XgL5Uf5Q6GUiUXbtzkqYbO5SP+WKMPY43LcOvLt11P+Oj2D9NlraT3eAzJP7Qmq0bICL0xK2ys0mGj3mlfPVKFmvBxy+XAyRUE9Xr1kaCBhVo8akcgxVOhfIuBH/tcIJm5Qp7Au+B7pwpKYGuHo=
addons:
  code_climate:
    repo_token: fb3478a949e8256ee2401c2b843d189dae34b756bfaf0ad7cec1a75ad5f7017b
env:
  global:
  - GH_REF: github.com/ng-next/ng-next-example.git
  - secure: "HdMbkApHi8qdZmwpd60oOVOiA3+bC7BWpWz420B7O9fXlzHr+GJj5pvi0tHPeR83ZRMCW5xW/1C04R0SPg/Indds+eIx/Oh72Yk5mz5Ay26+ZZ+2ZC5JcAbkzxeZmrK/PPbUdwtE1+UOpR7TXGGbW0JCQALwALh4XgsfiWUEljY="
  - secure: "cL9LZNZrss/noXWQcyq/AT1eU9gFcDiwggoehaSh4/1ucKHh0YL8MynhtIzbblhosYkRRwEitkuJIVwF7VvLRLSqF2yonAcvAlz1R32j/0tFsVDL0wVrHNdrv1EV1avit0hftkd+1IWXY0cAGFiMqtQXJZBiokuhdrSkXY0DXQo="
before_install:
- npm install -g jspm gulp codeclimate-test-reporter
- jspm config registries.github.auth $JSPM_GH_AUTH
install:
- npm install
after_success:
- gulp build-gh-pages
- chmod +x ./utilities/deploy-ghpages.sh
- npm run deploy
#after_script:
#- cat ./reports/coverage/report-lcov/lcov.info | codeclimate
